### PR TITLE
[WIP]Create zh_cn.lang

### PR DESCRIPTION
**Pull request by SettingDust**
Chinese

### CODE REVIEW

**Comment by JTK222** [comment]
Sorry for the massive waiting time, I kinda forgot about this :/
Is the translation ready to be merged or still wip?

**Comment by SettingDust** [comment]
Lang is ok. But not [json](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/blob/master/src/main/resources/assets/drpmedieval/arg/language_generators)

I have submitted this on Discord.

**Comment by JTK222** [comment]
This is for 1.12 anyways, right? In that case it's not supposed to be a json :3
Gonna merg it later today when I have time to publish a new version with the translation.

**Comment by SettingDust** [comment]
> This is for 1.12 anyways, right? In that case it's not supposed to be a json :3
> Gonna merg it later today when I have time to publish a new version with the translation.

Yes, 1.12.

**Comment by JTK222** [comment]
Sorry but 1.12 is no longer supported. You can use this as a resource pack if you want.
Sorry that I never got around merging this.

**Pull request closed without merging**
