### PR TITLE
Changed collision boxes of chairs

### PR DESCRIPTION
**Pull request by Tschipp**
I changed the collision boxes of chairs so that CustomNpc's can actually sit in them.

### CODE REVIEW

**Comment by JTK222** [comment]
I'll take a closer look at this once I am back home (in 8-14 days). But generally I am not a large fan of this Idea.
I can imagine making the Collision Boxes fit the model. But not just making it a specifc height.

**Comment by Tschipp** [comment]
The height is customizable for the chairs. They all align pixel perfect with the seat, of course you can still walk through the back of the chair. I'm not quite sure what you mean with specific height.

**Comment by JTK222** [comment]
The problem I have is that the clickable hitbox doesn't contain the majority of the model.
It wouldn't feel right that you can't interact/break it by clicking onto the back of the chairs.
I wouldn't mind to make the entity hitbox smaller however. (I've done it for the Rope Fence before)

**Comment by Tschipp** [comment]
That's actually not the case. I've only changed the Collision Box of the Chairs, not the Selection or Hit Box. This means the block still appears as large as it was before, but the collision box is smaller. You can still click on the back of the chair to sit.

**Comment by Tschipp** [comment]
So? How's it looking on this?

**Comment by JTK222** [comment]
Done in <https://www.curseforge.com/minecraft/mc-mods/dark-roleplay-medieval/files/2781663>

**Comment by Tschipp** [comment]
Great to hear!

**Pull request closed without merging**
